In [2]:
pip install numpy

In [3]:
import numpy as np


**numpy creating arrays, slicing and attributes.**


In [4]:
arr=np.array([10,20,30,40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [5]:
a=np.array([[10,20,30,40],[10,52,41,25],[62,12,24,35]])
print(a)
print(type(a))

[[10 20 30 40]
 [10 52 41 25]
 [62 12 24 35]]
<class 'numpy.ndarray'>


In [6]:
a=np.array([10,20,30,40])
print(a[1:])
print(type(a))


[20 30 40]
<class 'numpy.ndarray'>


In [7]:
a=np.array([10,20,30,40])
print(a[0:2])

[10 20]


In [8]:
a=np.array([10,20,30,40])
print(a[:3])

[10 20 30]


In [9]:
a=np.array([[10,20,30,40],[10,52,41,25]])
print(a)

[[10 20 30 40]
 [10 52 41 25]]


In [10]:
a=np.array([[10,20,30,40],[10,52,41,25]])
print(a[0:2,0:2])

[[10 20]
 [10 52]]


In [11]:
a=np.array([[10,20,30,40],[10,52,41,25]])
print(a[0:2,0:3])

[[10 20 30]
 [10 52 41]]


In [12]:
   a=np.array([[10,20,30,40],[10,52,41,25],[62,12,24,35]])
print(a[0,0:2])

[10 20]


In [13]:
a=np.array([[10,20,30,40],[10,52,41,25],[62,12,24,35]])
print(a[1,0:2])

[10 52]


In [14]:
a=np.array([[10,20,30,40],[10,52,41,25],[62,12,24,35]])
print(a[2,0:2])

[62 12]


In [15]:
a=np.array([[10,20,30,40],[10,52,41,25],[62,12,24,35]])
print(a[2,2])

24


In [16]:
#atrributes
a=np.array([[10,20,30,40],[10,52,41,25],[62,12,24,35]])
print(np.shape(a)) #shape of array
print(np.size(a)) #size of array no of elements
print(np.ndim(a))  #number of dimenstions
print(a.dtype) #data type of array

(3, 4)
12
2
int64


**inpecting a array**

In [17]:
import numpy as np
a=np.array([[10,20],[53,46]])
print(a)
print(a.shape) # rows,columns
print(len(a))# no of nested values
print(np.size(a))# no of elements
print(type(a)) # data type of variable
print(a.dtype) # data type of array
print(a.astype(float))# converstion of datatype of array elements

[[10 20]
 [53 46]]
(2, 2)
2
4
<class 'numpy.ndarray'>
int64
[[10. 20.]
 [53. 46.]]


**mathematical oprations and functions on array**


In [18]:
arr1=np.array([[10,20],[40,50]])
arr2=np.array([[110,120],[140,150]])
print(arr1)
print(arr2)
print(arr1+arr2)
print(np.add(arr1,arr2))

[[10 20]
 [40 50]]
[[110 120]
 [140 150]]
[[120 140]
 [180 200]]
[[120 140]
 [180 200]]


In [19]:
arr1=np.array([[10,20],[40,50]])
arr2=np.array([[110,120],[140,150]])
print(arr1)
print(arr2)
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[10 20]
 [40 50]]
[[110 120]
 [140 150]]
[[-100 -100]
 [-100 -100]]
[[-100 -100]
 [-100 -100]]


In [20]:
arr1=np.array([[10,20],[40,50]])
arr2=np.array([[110,120],[140,150]])
print(arr1)
print(arr2)
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[10 20]
 [40 50]]
[[110 120]
 [140 150]]
[[1100 2400]
 [5600 7500]]
[[1100 2400]
 [5600 7500]]


In [21]:
arr1=np.array([[10,20],[40,50]])
arr2=np.array([[110,120],[140,150]])
print(arr1)
print(arr2)
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[10 20]
 [40 50]]
[[110 120]
 [140 150]]
[[0.09090909 0.16666667]
 [0.28571429 0.33333333]]
[[0.09090909 0.16666667]
 [0.28571429 0.33333333]]


In [22]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([2])
print(np.power(arr1,arr2))

[ 1  4  9 16 25]


In [23]:
arr1=np.array([ 1 , 4 , 9, 16, 25])

print(np.sqrt(arr1))

[1. 2. 3. 4. 5.]


** Combining and splitting Arrays**
 **bold text**

In [24]:
a=[1,2,3,4,5]
b=[10,20,30,40,50]
print(a+b)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


In [25]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print(np.concatenate([arr1,arr2]))

[ 1  2  3  4  5 10 20 30 40 50]


In [26]:
arr1=np.array([[1,2],[4,5]])
arr2=np.array([[10,20],[40,50]])

print(np.concatenate([arr1,arr2]))

[[ 1  2]
 [ 4  5]
 [10 20]
 [40 50]]


In [57]:
arr1=np.array([[1,2],[4,5]])
arr2=np.array([[10,20],[40,50]])

print(np.concatenate([arr1,arr2], axis=1))

[[ 1  2 10 20]
 [ 4  5 40 50]]


In [28]:
print(np.hstack([arr1,arr2])) # horizonatal concatination

[[ 1  2 10 20]
 [ 4  5 40 50]]


In [29]:
print(np.vstack([arr1,arr2]))  # vertical concatination

[[ 1  2]
 [ 4  5]
 [10 20]
 [40 50]]


In [30]:
a=np.array([1,2,3,4,5,6])
b=np.array_split(a,3)
print(b)
print(b[1])

[array([1, 2]), array([3, 4]), array([5, 6])]
[3 4]


 Adding and Removing elements in the arrays

In [31]:
import numpy as np


In [32]:
a= np.array([20,60,40,60])
print(np.append(a,80))

[20 60 40 60 80]


In [33]:
a= np.array([[20,60],[40,60]])
print(np.append(a,80))

[20 60 40 60 80]


In [34]:
a= np.array([[20,60],[40,60]])
print(np.append(a,[80,12]))

[20 60 40 60 80 12]


In [35]:
a= np.array([20,60,40,60])
print(np.insert(a,1,20)) #array,index,value

[20 20 60 40 60]


In [36]:
a= np.array([[20,60],[40,60]])
print(np.insert(a,1,20))

[20 20 60 40 60]


In [37]:
a= np.array([[20,60],[40,60]])
print(np.insert(a,1,[20,30]))

[20 20 30 60 40 60]


In [38]:
a= np.array([[20,60],[40,60]])
print(np.insert(a,1,[20,30], axis=0))

[[20 60]
 [20 30]
 [40 60]]


In [39]:
a= np.array([[20,60],[40,60]])
print(np.insert(a,1,[30], axis=0))

[[20 60]
 [30 30]
 [40 60]]


In [40]:
a= np.array([[20,60],[40,60]])
print(np.insert(a,[1,2],[30], axis=0))

[[20 60]
 [30 30]
 [40 60]
 [30 30]]


In [41]:
print(a)
print(np.delete(a,1))

[[20 60]
 [40 60]]
[20 40 60]


In [42]:
print(a)
print(np.delete(a,1, axis=0))

[[20 60]
 [40 60]]
[[20 60]]


In [43]:
print(a)
print(np.delete(a,1, axis=1))

[[20 60]
 [40 60]]
[[20]
 [40]]


** Aggregating functions in arrays**





In [44]:
import numpy as np
a=np.array([20,40,60,70])
print(a)

[20 40 60 70]


In [45]:
print(np.sum(a))

190


In [46]:
print(np.min(a))

20


In [47]:
print(np.max(a))

70


In [48]:
print(np.size(a))

4


In [49]:
print(np.mean(a))

47.5


In [50]:
print(np.cumsum(a))

[ 20  60 120 190]


In [51]:
print(np.cumprod(a))

[     20     800   48000 3360000]


**Statistical functions in arrays**




In [52]:
a=[100,150,199,200,250,130]
b=[10,50,30,40,30,10]

price=np.array(a)
quantity=np.array(b)
print(price,"\n",quantity)
print()
c=np.cumprod([price,quantity], axis=0)
print(c)
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]
31270


In [53]:
import numpy as np
import statistics as stats
baked_food=[200,150,150,130,200,220,170,188]
a =np.array(baked_food)
print(np.mean(baked_food)) # sum of all the values/number of values
print(np.median(baked_food)) # central value after sorting
print(stats.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))

176.0
179.0
200
29.017236257093817
842.0


In [54]:
#-1 represent inversely proportional relationship
# 1 represents proportional relationship
# 0 means no relationship

tobacco_consumption =[30,50,10,30,50,40]
deaths=[100,120,70,100,120,112]

print(np.corrcoef([tobacco_consumption,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [55]:
price = [300,100,350,150,200]
sales =[10,20,7,17,3]


print(np.corrcoef([price,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
